- name: Create /etc/uwsgi
  file: path=/etc/uwsgi/vassals state=directory

- name: uwsgi.ini is loaded
  template: src={{project_name}}_uwsgi.ini dest=/etc/uwsgi/vassals backup=no

- name: uwsgi daemon is loaded
  template: src=uwsgi.conf dest=/etc/init/ backup=no

- name: uwsgi daemon is started
  service: name=uwsgi state=reloaded
